services:
 dns:
  container_name: dns
  hostname: dns
  image: dns
  ports: 
   - 53:53/udp
   - 53:53/tcp
   - 853:853/tcp
  volumes:
   - ../certificate:/etc/letsencrypt/
  networks:
   - dns

networks:
 dns:
  name: DoH
  external: true
