services:
  master_db:
    image: correba/woody_database
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_password
    secrets:
      - db_password
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      placement:
        constraints:
          - node.hostname == vps-mateo

  redis:
    image: redis:6.2-alpine
    environment:
      - REDIS_PASSWORD=/run/secrets/redis_password
    secrets:
      - redis_password
    networks:
      - cache

  api:
    image: correba/woody_api
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_password
      - MYSQL_HOST_MASTER=master_db
      - MYSQL_HOST_SLAVE=slave_db
      - REDIS_HOST=redis
      - REDIS_PASSWORD=/run/secrets/redis_password
    secrets:
      - db_password
      - redis_password
    networks:
      - db
      - api
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

    deploy:
      replicas: 3

  front:
    image: correba/woody_front
    networks:
      - front
    deploy:
      replicas: 3

  reverse:
    image: correba/woody_rp
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
    networks:
      - front
      - api
    deploy:
      mode: global

networks:
  api:
  cache:
  db:
  front:

secrets:
  db_password:
    file: secrets/db_password.txt
  redis_password:
    file: secrets/redis_password.txt
