services:
  master_db:
    image: correba/woody_master_database
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 15s
    deploy:
      placement:
        constraints:
          - node.hostname == vps-mateo

  slave_db:
    image: correba/woody_slave_database
    cap_add:
      - SYS_NICE
    depends_on:
      - master_db
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 15s
    deploy:
      placement:
        constraints:
          - node.hostname == vps-louish

  redis:
    image: redis:6.2-alpine
    networks:
      - cache

  api:
    image: correba/woody_api
    depends_on:
      - redis
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_HOST_MASTER=master_db
      - MYSQL_HOST_SLAVE=slave_db
      - REDIS_HOST=redis
    networks:
      - db
      - api
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/ping"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 15s
    deploy:
      replicas: 3

  front:
    image: correba/woody_front
    networks:
      - front
    deploy:
      replicas: 3

  reverse:
    image: correba/woody_rp
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
    networks:
      - front
      - api
    deploy:
      mode: global

networks:
  api:
  cache:
  db:
  front: