services:
  db:
    image: correba/woody_database
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'

  api:
    image: correba/woody_api
    restart: always
    links:
      - "db"

  front:
    image: correba/woody_front

  reverse:
    image: correba/woody_rp
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
