version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    networks:
      - api
  php:
    build: ./php
    image: php
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${USER_PASS}
    volumes:
      - ./html/www:/var/www/html/www
    networks:
      - api
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${USER_PASS}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - db

networks:
  api:
  db:
